"""add description to posts

Revision ID: 078debe32354
Revises: 555e5965f28c
Create Date: 2026-08-28 08:22:06.155474

"""
from typing import Union
import collections.abc

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '078debe32354'
down_revision: Union[str, collections.abc[str], None] = '555e5965f28c'
branch_labels: Union[str, collections.abc[str], None] = None
depends_on: Union[str, collections.abc[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'description')
    # ### end Alembic commands ###
