"""add created_by to categories

Revision ID: ca20138ccdf4
Revises: 502ba0329a00
Create Date: 2026-08-23 12:59:26.448957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca20138ccdf4'
down_revision: Union[str, Sequence[str], None] = '502ba0329a00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'created_by_id')
    # ### end Alembic commands ###
